--- #YAML:1.0
name:               MP3-CreateInlayCard
version:            0.06
abstract:           create a CD inlay label for a directory of MP3 files
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:               0
    File::Find::Rule:  0
    HTML::Template:    0
    Music::Tag:        0
    Music::Tag::MP3:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
